apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: mypostgres
          ports:
            - containerPort: 5432
          env:
           - name: POSTGRES_PASSWORD
             value: mysecretpassword
           - name: PGDATA
             value: /var/lib/postgresql/data/test
          volumeMounts:
          - name: postgresql-data
            mountPath: /var/lib/postgresql/data
            claimName: postgresql-data
          resources:
            limits:
              memory: 256Mi
              cpu: 400m
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi